# Shared parameter definitions used by both pages.
# Each tuple: (slug, label_p1, label_p2, lo, hi, default, step, unit, desc)

PARAMS = [
    ("starlink_mini_constant_load",
     "Satellite internet (W)", "Starlink Mini constant load",
     20, 75, 35, 1, "W",
     "Constant draw regardless of time of day or work status."),
    ("laptop_workday_load",
     "Laptop — work hours (W)", "Laptop workday load",
     30, 150, 75, 1, "W",
     "Added to load only during work hours (9 am–5 pm)."),
    ("monitor_workday_load",
     "Monitor — work hours (W)", "Monitor workday load",
     10, 100, 35, 1, "W",
     "Added to load only during work hours alongside the laptop."),
    ("ac_compressor_load",
     "Air conditioner (W)", "AC compressor load",
     400, 1000, 675, 25, "W",
     "Power draw when the thermostat calls for cooling (8,000 BTU unit)."),
    ("battery_capacity",
     "Battery bank size (kWh)", "Battery capacity",
     1.0, 10.0, 2.5, 0.1, "kWh",
     "Sets capacity, minimum SOC floor (20 %), and target SOC threshold."),
    ("initial_battery_soc",
     "Starting charge level (%)", "Initial battery SOC",
     20, 100, 80, 1, "%",
     "Starting state of charge: E(0) = SOC₀/100 × E_cap."),
    ("solar_array_rating",
     "Solar panels (W)", "Solar array rating",
     100, 1600, 400, 25, "W",
     "Peak DC nameplate wattage; effective peak is ~56 % after de-rating."),
    ("wind_turbine_rating",
     "Wind turbine (W)", "Wind turbine rating",
     100, 2000, 500, 25, "W",
     "Rated output; model scales the base wind curve proportionally."),
    ("generator_rated_output",
     "Generator size (W)", "Generator rated output",
     500, 6000, 3000, 100, "W",
     "Nameplate wattage of the generator. P_limit = P_rated × gen_pct / 100."),
    ("generator_output_cap",
     "Output limit (%)", "Generator output cap",
     25, 100, 85, 1, "%",
     "Percentage of rated output allowed. Also determines fuel rate step."),
    ("generator_recharge_target",
     "Recharge to this level (%)", "Generator recharge target",
     40, 95, 75, 1, "%",
     "Generator turns off once battery SOC reaches this value."),
]
